import argparse
import concurrent.futures
import json
import os
import sys
import traceback
from pathlib import Path

import mujoco as mj
import torch
from tqdm import tqdm


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

DEFAULT_BACKEND = "gmr_baseline"
DEFAULT_RETARGETED_ROOT = f"motion_data/BEAT2/retargeted/{DEFAULT_BACKEND}"
DEFAULT_ROBOT_CACHE_ROOT = f"motion_data/BEAT2/eval_cache/{DEFAULT_BACKEND}"

from general_motion_retargeting import ROBOT_XML_DICT, retarget_smplx_file_to_motion, save_retargeted_motion
from scripts.beat2_processing.common import (
    build_robot_cache_from_motion,
    load_smplx_joints,
    load_smplx_model,
    read_manifest,
    resolve_repo_path,
    save_robot_cache,
    save_source_cache,
    to_pelvis_relative,
)
from scripts.beat2_to_robot import build_amass_compatible_file

_WORKER_BODY_MODEL = None
_WORKER_ROBOT_MODEL = None


def init_worker(model_root: str, robot: str) -> None:
    global _WORKER_BODY_MODEL
    global _WORKER_ROBOT_MODEL

    torch.set_num_threads(1)
    _WORKER_BODY_MODEL = load_smplx_model(Path(model_root))
    _WORKER_BODY_MODEL.eval()
    _WORKER_ROBOT_MODEL = mj.MjModel.from_xml_path(str(ROBOT_XML_DICT[robot]))


def process_row(task: dict) -> dict:
    row = task["row"]
    args = task["args"]

    clip_id = row["clip_id"]
    src_npz = Path(args["src_root"]) / row["npz_filename"]
    converted_path = Path(args["converted_root"]) / f"{clip_id}_amass_compat.npz"
    motion_path = Path(args["retargeted_root"]) / f"{clip_id}_{args['robot']}.pkl"
    source_cache_path = Path(args["source_cache_root"]) / f"{clip_id}_source_eval.npz"
    robot_cache_path = Path(args["robot_cache_root"]) / f"{clip_id}_{args['robot']}_eval.npz"

    if args["skip_existing"] and motion_path.exists() and robot_cache_path.exists():
        return {"status": "skipped", "clip_id": clip_id}

    build_amass_compatible_file(
        src_npz=src_npz,
        converted_path=converted_path,
        source_up_axis=args["source_up_axis"],
    )

    joints_6, pelvis, source_fps = load_smplx_joints(converted_path, _WORKER_BODY_MODEL)
    source_positions = to_pelvis_relative(joints_6, pelvis)
    save_source_cache(source_cache_path, row, source_positions, source_fps)

    motion = retarget_smplx_file_to_motion(
        smplx_file=converted_path,
        robot=args["robot"],
        model_root=args["model_root"],
        backend=args["backend"],
        quiet=not args["verbose_child"],
    )
    save_retargeted_motion(motion_path, motion)

    robot_positions, dof_names, dof_pos, scr, collision_frame_mask, collision_pair_counts = (
        build_robot_cache_from_motion(
            _WORKER_ROBOT_MODEL,
            {
                "fps": motion.fps,
                "root_pos": motion.root_pos,
                "root_rot_wxyz": motion.root_rot_wxyz,
                "dof_pos": motion.dof_pos,
            },
        )
    )
    save_robot_cache(
        robot_cache_path,
        row,
        backend=args["backend"],
        positions=robot_positions,
        fps=motion.fps,
        dof_names=dof_names,
        dof_pos=dof_pos,
        self_collision_rate=scr,
        collision_frame_mask=collision_frame_mask,
        collision_pair_counts=collision_pair_counts,
    )

    return {"status": "completed", "clip_id": clip_id}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Precompute BEAT2 converted motions, source caches, retargeted motions, and robot caches."
    )
    parser.add_argument(
        "--manifest",
        default="motion_data/BEAT2/manifests/beat2_emotion_manifest.csv",
        help="Manifest CSV generated by build_emotion_manifest.py.",
    )
    parser.add_argument(
        "--src_root",
        default="/home/vergil/dataset/BEAT2/beat_english_v2.0.0/smplxflame_30",
        help="Folder containing BEAT2 SMPL-X/FLAME .npz clips.",
    )
    parser.add_argument(
        "--converted_root",
        default="motion_data/BEAT2/converted",
        help="Output folder for AMASS-compatible .npz files.",
    )
    parser.add_argument(
        "--retargeted_root",
        default=DEFAULT_RETARGETED_ROOT,
        help="Output folder for retargeted robot .pkl files. Defaults to motion_data/BEAT2/retargeted/<backend>.",
    )
    parser.add_argument(
        "--source_cache_root",
        default="motion_data/BEAT2/eval_cache/source",
        help="Output folder for source-side evaluation caches.",
    )
    parser.add_argument(
        "--robot_cache_root",
        default=DEFAULT_ROBOT_CACHE_ROOT,
        help="Output folder for robot-side evaluation caches. Defaults to motion_data/BEAT2/eval_cache/<backend>.",
    )
    parser.add_argument(
        "--model_root",
        default="assets/body_models",
        help="SMPL-X model root, relative to the repository root unless absolute.",
    )
    parser.add_argument("--robot", default="nao", help="Target robot name.")
    parser.add_argument(
        "--backend",
        default="gmr_baseline",
        help="Retarget backend name. Current implementation supports gmr_baseline and gmr_velocity.",
    )
    parser.add_argument(
        "--source_up_axis",
        choices=["z", "y"],
        default="y",
        help="Up axis of source motions before conversion. BEAT2/NAO baseline uses y.",
    )
    parser.add_argument("--limit", type=int, default=None, help="Only process the first N manifest rows.")
    parser.add_argument(
        "--verbose_child",
        action="store_true",
        help="Show verbose child-process retargeting diagnostics.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of clips to process in parallel.",
    )
    parser.add_argument(
        "--skip_existing",
        action="store_true",
        help="Skip clips whose retargeted pkl and robot cache already exist.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.workers < 1:
        raise ValueError("--workers must be >= 1")
    args.workers = min(args.workers, os.cpu_count() or args.workers)
    if args.retargeted_root == DEFAULT_RETARGETED_ROOT:
        args.retargeted_root = f"motion_data/BEAT2/retargeted/{args.backend}"
    if args.robot_cache_root == DEFAULT_ROBOT_CACHE_ROOT:
        args.robot_cache_root = f"motion_data/BEAT2/eval_cache/{args.backend}"

    manifest_path = resolve_repo_path(REPO_ROOT, args.manifest).resolve()
    src_root = Path(args.src_root).expanduser().resolve()
    converted_root = resolve_repo_path(REPO_ROOT, args.converted_root).resolve()
    retargeted_root = resolve_repo_path(REPO_ROOT, args.retargeted_root).resolve()
    source_cache_root = resolve_repo_path(REPO_ROOT, args.source_cache_root).resolve()
    robot_cache_root = resolve_repo_path(REPO_ROOT, args.robot_cache_root).resolve()
    model_root = resolve_repo_path(REPO_ROOT, args.model_root).resolve()

    rows = read_manifest(manifest_path)
    if args.limit is not None:
        rows = rows[: args.limit]

    completed = 0
    failed = []
    worker_args = {
        "src_root": str(src_root),
        "converted_root": str(converted_root),
        "retargeted_root": str(retargeted_root),
        "source_cache_root": str(source_cache_root),
        "robot_cache_root": str(robot_cache_root),
        "model_root": str(model_root),
        "robot": args.robot,
        "backend": args.backend,
        "source_up_axis": args.source_up_axis,
        "verbose_child": args.verbose_child,
        "skip_existing": args.skip_existing,
    }

    tasks = [{"row": row, "args": worker_args} for row in rows]
    with concurrent.futures.ProcessPoolExecutor(
        max_workers=args.workers,
        initializer=init_worker,
        initargs=(str(model_root), args.robot),
    ) as executor:
        futures = {executor.submit(process_row, task): task for task in tasks}
        progress = tqdm(
            concurrent.futures.as_completed(futures),
            total=len(futures),
            desc=f"Precompute BEAT2->{args.robot} ({args.backend})",
            unit="clip",
        )
        for future in progress:
            task = futures[future]
            try:
                future.result()
                completed += 1
            except Exception as exc:
                failed.append(
                    {
                        "clip_id": task["row"]["clip_id"],
                        "error": repr(exc),
                        "traceback": "".join(
                            traceback.format_exception(type(exc), exc, exc.__traceback__)
                        ),
                    }
                )
                tqdm.write(f"[FAIL] {task['row']['clip_id']}: {exc!r}")
            progress.set_postfix(done=completed, failed=len(failed))

    retargeted_root.mkdir(parents=True, exist_ok=True)
    failure_path = retargeted_root / f"{args.robot}_{args.backend}_precompute_failures.json"
    if failed:
        failure_path.write_text(json.dumps(failed, indent=2), encoding="utf-8")
        print(f"[WARN] Wrote failures to {failure_path}")
    elif failure_path.exists():
        failure_path.unlink()

    print(
        f"[DONE] clips={len(rows)} completed={completed} failed={len(failed)} "
        f"retargeted_root={retargeted_root}"
    )


if __name__ == "__main__":
    main()
