import argparse
import concurrent.futures
import csv
import json
import sys
from pathlib import Path

from tqdm import tqdm


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.beat2_to_robot import build_amass_compatible_file, run_retarget


def process_row(task: dict) -> dict:
    row = task["row"]
    args = task["args"]

    npz_filename = row["npz_filename"]
    src_npz = Path(args["src_root"]) / npz_filename
    stem = Path(npz_filename).stem
    converted_path = Path(args["converted_root"]) / f"{stem}_amass_compat.npz"
    save_path = Path(args["save_root"]) / f"{stem}_{args['robot']}.pkl"

    if save_path.exists() and not args["overwrite"]:
        return {"status": "skipped", "npz_filename": npz_filename}

    build_amass_compatible_file(
        src_npz=src_npz,
        converted_path=converted_path,
        source_up_axis=args["source_up_axis"],
    )
    run_retarget(
        repo_root=Path(args["repo_root"]),
        smplx_file=converted_path,
        robot=args["robot"],
        save_path=save_path,
        rate_limit=args["rate_limit"],
        headless=True,
        quiet=not args["verbose_child"],
    )
    return {"status": "completed", "npz_filename": npz_filename}


def read_manifest(manifest_path: Path) -> list[dict]:
    with manifest_path.open(newline="") as file:
        return list(csv.DictReader(file))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Batch retarget BEAT2 English Speech clips to NAO using the Section 1 manifest."
    )
    parser.add_argument(
        "--manifest",
        default="motion_data/BEAT2/manifests/beat2_emotion_manifest.csv",
        help="Manifest CSV generated by build_emotion_manifest.py.",
    )
    parser.add_argument(
        "--src_root",
        default="/home/vergil/dataset/BEAT2/beat_english_v2.0.0/smplxflame_30",
        help="Folder containing BEAT2 SMPL-X/FLAME .npz clips.",
    )
    parser.add_argument(
        "--converted_root",
        default="motion_data/BEAT2/converted",
        help="Output folder for AMASS-compatible .npz files.",
    )
    parser.add_argument(
        "--save_root",
        default="motion_data/BEAT2/retargeted",
        help="Output folder for retargeted robot .pkl files.",
    )
    parser.add_argument(
        "--robot",
        default="nao",
        help="Target robot name.",
    )
    parser.add_argument(
        "--source_up_axis",
        choices=["z", "y"],
        default="y",
        help="Up axis of source motions before conversion. BEAT2/NAO baseline uses y.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Only process the first N manifest rows.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Recompute clips even when the target .pkl already exists.",
    )
    parser.add_argument(
        "--rate_limit",
        action="store_true",
        help="Pass --rate_limit to smplx_to_robot.py.",
    )
    parser.add_argument(
        "--verbose_child",
        action="store_true",
        help="Show verbose child-process retargeting diagnostics.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of clips to retarget in parallel. Start with 2 or 3.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    manifest_path = (REPO_ROOT / args.manifest).resolve()
    src_root = Path(args.src_root).expanduser().resolve()
    converted_root = (REPO_ROOT / args.converted_root).resolve()
    save_root = (REPO_ROOT / args.save_root).resolve()

    rows = read_manifest(manifest_path)
    if args.limit is not None:
        rows = rows[: args.limit]

    completed = 0
    skipped = 0
    failed = []

    worker_args = {
        "repo_root": str(REPO_ROOT),
        "src_root": str(src_root),
        "converted_root": str(converted_root),
        "save_root": str(save_root),
        "robot": args.robot,
        "source_up_axis": args.source_up_axis,
        "overwrite": args.overwrite,
        "rate_limit": args.rate_limit,
        "verbose_child": args.verbose_child,
    }

    if args.workers > 1:
        tasks = [{"row": row, "args": worker_args} for row in rows]
        with concurrent.futures.ProcessPoolExecutor(max_workers=args.workers) as executor:
            futures = [executor.submit(process_row, task) for task in tasks]
            progress = tqdm(
                concurrent.futures.as_completed(futures),
                total=len(futures),
                desc=f"Retarget BEAT2->{args.robot}",
                unit="clip",
            )
            for future in progress:
                try:
                    result = future.result()
                    if result["status"] == "skipped":
                        skipped += 1
                    else:
                        completed += 1
                except Exception as exc:
                    failed.append({"error": repr(exc)})
                    tqdm.write(f"[FAIL] {exc!r}")
                progress.set_postfix(done=completed, skipped=skipped, failed=len(failed))
    else:
        progress = tqdm(rows, desc=f"Retarget BEAT2->{args.robot}", unit="clip")
        for row in progress:
            npz_filename = row["npz_filename"]
            progress.set_postfix_str(npz_filename)
            try:
                result = process_row({"row": row, "args": worker_args})
                if result["status"] == "skipped":
                    skipped += 1
                else:
                    completed += 1
            except Exception as exc:
                failed.append(
                    {
                        "clip_id": row.get("clip_id", Path(npz_filename).stem),
                        "npz_filename": npz_filename,
                        "error": repr(exc),
                    }
                )
                tqdm.write(f"[FAIL] {npz_filename}: {exc!r}")

            progress.set_postfix(done=completed, skipped=skipped, failed=len(failed))

    save_root.mkdir(parents=True, exist_ok=True)
    if failed:
        failure_path = save_root / f"{args.robot}_retarget_failures.json"
        with failure_path.open("w") as file:
            json.dump(failed, file, indent=2)
        print(f"[WARN] Wrote failures to {failure_path}")

    print(
        f"[DONE] clips={len(rows)} completed={completed} skipped={skipped} "
        f"failed={len(failed)} save_root={save_root}"
    )


if __name__ == "__main__":
    main()
